# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Optional, but pins the version for reproducibility.
    rev: v0.4.4
    hooks:
    # Run the linter.
    -   id: ruff
        args: [--fix] # Automatically fix what it can
    # Run the formatter.
    -   id: ruff-format
